# Generated by Django 6.0.3 on 2026-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecibelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(default='Sensor-001', max_length=50)),
                ('db_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Cagayan De Oro City', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
